#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
                 KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,
                                                                            KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, //right 1

                 OSM(MOD_LSFT), KC_Q, KC_W, KC_E, KC_R, KC_T, //left 2

                                                                            KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL, //right 2

                 LSFT_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, LT(2,KC_G),
                                                                            KC_H, KC_J, KC_K, KC_L, KC_SCLN, RSFT_T(KC_QUOT),

                 LGUI_T(KC_LEFT), LT(1,KC_Z), KC_X, KC_C, LT(1,KC_V), KC_B,
                                                                          CW_TOGG, KC_UNDS,

                                                                          KC_N, LT(1,KC_M), KC_COMM, KC_DOT, LT(1,KC_SLSH), RGUI_T(KC_RIGHT),

                 LALT_T(KC_DOWN),    LCTL_T(KC_TAB),    KC_BSPC,

                                                                         LT(1, KC_SPC),    RCTL_T(KC_ENT),   RALT_T(KC_UP)),

	[1] = LAYOUT(
                 KC_F11, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
                                                                          KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F12,
                 KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,
                                                                          KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_UNDS,
                 KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,
                                                                          KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
                 KC_NO, KC_0, KC_DQUO, KC_UNDS, KC_BSLS, KC_PIPE, // 4 left row
                                                                          KC_NO, KC_NO,
                                                                          KC_EQL, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_DEL,
                 KC_NO, KC_NO, KC_NO,
                                                                          KC_NO, KC_NO, KC_NO),
	[2] = LAYOUT(
                 RGB_TOG, RGB_MOD, RGB_VAI, RGB_VAD, RGB_SPI, RGB_SPD,

                                                                          QK_MACRO_3, QK_MACRO_0, QK_MACRO_1,QK_MACRO_2, KC_VOLD, KC_VOLU,

                 BL_TOGG, BL_STEP, BL_UP, BL_DOWN, KC_NO, KC_NO,

                                                                           KC_HOME, LCTL(KC_LEFT), LCTL(KC_RIGHT),KC_END,  KC_NO, QK_MACRO_1,

                 KC_NO, KC_NO,KC_NO, KC_NO, KC_NO, KC_NO,

                                                                          KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, QK_MACRO_0,

                 KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                                                                          KC_NO, KC_NO,

                                                                           LGUI(LCTL(KC_LEFT)),KC_PAGE_DOWN,KC_PAGE_UP, LGUI(LCTL(KC_RIGHT)),QK_MACRO_4, LCTL(LALT(KC_DEL)),

                 KC_NO, KC_NO, KC_NO,

                                                                          KC_NO,  KC_NO, LALT(KC_X))

	/* [3] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
    /*              KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
    /*              KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
    /*              KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS) */
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(" <- ");
                return false;
            case QK_MACRO_1:
                SEND_STRING(" %in% ");
                return false;
            case QK_MACRO_2:
                SEND_STRING(" %>% ");
                return false;
            case QK_MACRO_3:
                SEND_STRING("```{r}"SS_TAP(X_ENT)SS_TAP(X_ENT)"```"SS_TAP(X_UP));
                return false;
            case QK_MACRO_4:
                SEND_STRING(SS_TAP(X_SPC)SS_TAP(X_M)SS_TAP(X_X)SS_TAP(X_R));
                return false;
        }
    }

    return true;
};


const uint16_t PROGMEM test_combo1[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM test_combo2[] = {KC_F, KC_J, COMBO_END};
const uint16_t PROGMEM test_combo3[] = {KC_E, KC_I, COMBO_END};
const uint16_t PROGMEM test_combo4[] = {KC_S, KC_L, COMBO_END};
combo_t key_combos[COMBO_COUNT] = {
    COMBO(test_combo1, KC_ESC),
    COMBO(test_combo2, OSM(MOD_LSFT)), // keycodes with modifiers are possible too!
    COMBO(test_combo3, CW_TOGG),
    COMBO(test_combo4, KC_UNDS)
};
